### ISSUE TITLE
ENS Protocol - Deployment - Could not find @ensdomains/ens/contracts/ENS.sol

### ISSUE THREAD

**Issue by chrishobcroft** [empowerthedao/ens-aragon-app#1]
Steps to recreate:

- Following the instructions here: https://github.com/empowerthedao/ens-aragon-app/tree/master/ens-protocol

- Run `npm install`

- Run `ganache-cli` in a separate window

- Run `truffle migrate` (from the ens-protocol folder)

- See error:

```
chrishobcroft@thinkpad:~/ens-aragon-app/ens-protocol$ truffle migrate

Compiling your contracts...
===========================
Error: Error: Could not find @ensdomains/ens/contracts/ENS.sol from any sources; imported from /home/chrishobcroft/ens-aragon-app/ens-protocol/contracts/BaseRegistrar.sol
    at Object.compile (/home/chrishobcroft/node/lib/node_modules/truffle/build/webpack:/packages/truffle-workflow-compile/legacy/index.js:72:1)
Truffle v5.0.30 (core: 5.0.30)
Node v10.16.0
```

It seems that ENS contracts are required to be downloaded - suggest adding a step in the instructions for what to download, and where to locate it.

**Comment by willjgriff** [comment]
I don't believe your `npm install` completed properly. Remove `node_modules` folder and try again. Make sure you run `npm install` inside the `ens-protocol` directory.

**Comment by chrishobcroft** [comment]
OK, that seemed to work.

Perhaps update to make it more clear
